### ISSUE TITLE
trouble to get the number of row count in a SELECT statements

### ISSUE THREAD

**Issue by camous** [chilltemp/tedious-promises#6]
I'm facing trouble to get the number of results row (my use case requires to have exactly one result per SQL command, otherwise it's an error). I made tedious promise working for everything except this rows count check. (I'm discovering promises ...)

```
promises.push(tp
    .sql(command)
    .execute()
    .then(consolidate.bind(null, entities[property]))
    .fail(function (error) {
        client.trackException(new Error('Failure when querying database'),{ 'query' : command, 'details' : error.message});
        console.log('failure with ' + command + '\n' + error.message);
}));
```

```
function consolidate(input, data) {
    for (var property in data[0])
        input[property] = data[0][property];
}
```

consolidate method is only called when there is one or more results, but not 0.
I've tried to switch the processing into then() body, but the javascript context wasn't the correct one (wrong entities[property] reference, the last one I assume (it's a loop)).

```
promises.push(tp
    .sql(command)
    .execute()
    .then(function(results){

    if(results.length == 1){
        entities[property] = results[0]; // WRONG CONTEXT
    }else{
        // either 0 or > 1 isn't correct
        console.log('lookup failure with ' + command);
    }
})
    .fail(function (error) {
        client.trackException(new Error('Failure when querying database'),{ 'query' : command, 'details' : error.message});
        console.log('failure with ' + command + '\n' + error.message);
}));
```

any hints/direction ?
regards

**Comment by chilltemp** [comment]
The first syntax is really confusing.  bind(null, something) sets the default first parameter, but since it will never be used since TP will pass the parameter in.  Also, I don't see how you would get 'property' in the consolidate function.  You could use bind to set the default 2nd & 3rd parameters instead of the first, but I'll recommend against this as it's confusing.

Your second syntax is the most common one to use.  The problem is likely that you are using async code within a loop.  The variable 'property' will have changed by the time the async code is executed.  This solution for this is to use a function to create a new variable scope.  See this post for more details:
http://stackoverflow.com/q/750486/28736

Generally, I'd advise you to separate your loop from the details of what it does.  

``` js
var promises = [];
for(var property in entities) {
  promises.push(sampleFunction(entities, property));
}

function sampleFunction(entities, property) {
  return tp.sql(command) // return the promise
    .execute()
    .then(function(results) {
      if(results.length == 1){
        entities[property] = results[0]; // should work now
      } else {
        // either 0 or > 1 isn't correct
        console.log('lookup failure with ' + command);
      }
    })
    .fail(function (error) {
      client.trackException(new Error('Failure when querying database'),{ 'query' : command, 'details' : error.message});
      console.log('failure with ' + command + '\n' + error.message);
    });
}
```

**Comment by camous** [comment]
Thanks for the better understanding about js scope. Thanks to your help I was able to fix the scope within the loop and perform my use case in the correct way.
